version: "3"
services:
  influxdb:
    image: "influxdb:latest"
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
  garie-lighthouse:
    build: "."
    volumes:
      - ./reports:/usr/src/garie-lighthouse/reports
    ports:
      - 3000:3000
    environment:
      - HOST=influxdb  
    depends_on:
      - influxdb
